import re

txt = '<?php include "../Template/Navigation/frontend_navigation.php"; ?>'

re1 = '(.)'  # Any Single Character 1
re2 = '(.)'  # Any Single Character 2
re3 = '([a-z])'  # Any Single Word Character (Not Whitespace) 1
re4 = '([a-z])'  # Any Single Word Character (Not Whitespace) 2
re5 = '([a-z])'  # Any Single Word Character (Not Whitespace) 3
re6 = '.*?'  # Non-greedy match on filler
re7 = '.'  # Uninteresting: c
re8 = '.*?'  # Non-greedy match on filler
re9 = '.'  # Uninteresting: c
re10 = '.*?'  # Non-greedy match on filler
re11 = '.'  # Uninteresting: c
re12 = '.*?'  # Non-greedy match on filler
re13 = '.'  # Uninteresting: c
re14 = '.*?'  # Non-greedy match on filler
re15 = '.'  # Uninteresting: c
re16 = '.*?'  # Non-greedy match on filler
re17 = '.'  # Uninteresting: c
re18 = '.*?'  # Non-greedy match on filler
re19 = '.'  # Uninteresting: c
re20 = '.*?'  # Non-greedy match on filler
re21 = '.'  # Uninteresting: c
re22 = '.*?'  # Non-greedy match on filler
re23 = '.'  # Uninteresting: c
re24 = '.*?'  # Non-greedy match on filler
re25 = '.'  # Uninteresting: c
re26 = '.*?'  # Non-greedy match on filler
re27 = '.'  # Uninteresting: c
re28 = '.*?'  # Non-greedy match on filler
re29 = '.'  # Uninteresting: c
re30 = '.*?'  # Non-greedy match on filler
re31 = '.'  # Uninteresting: c
re32 = '.*?'  # Non-greedy match on filler
re33 = '.'  # Uninteresting: c
re34 = '.*?'  # Non-greedy match on filler
re35 = '.'  # Uninteresting: c
re36 = '.*?'  # Non-greedy match on filler
re37 = '.'  # Uninteresting: c
re38 = '.*?'  # Non-greedy match on filler
re39 = '.'  # Uninteresting: c
re40 = '.*?'  # Non-greedy match on filler
re41 = '.'  # Uninteresting: c
re42 = '.*?'  # Non-greedy match on filler
re43 = '.'  # Uninteresting: c
re44 = '.*?'  # Non-greedy match on filler
re45 = '.'  # Uninteresting: c
re46 = '.*?'  # Non-greedy match on filler
re47 = '.'  # Uninteresting: c
re48 = '.*?'  # Non-greedy match on filler
re49 = '.'  # Uninteresting: c
re50 = '.*?'  # Non-greedy match on filler
re51 = '.'  # Uninteresting: c
re52 = '.*?'  # Non-greedy match on filler
re53 = '.'  # Uninteresting: c
re54 = '.*?'  # Non-greedy match on filler
re55 = '.'  # Uninteresting: c
re56 = '.*?'  # Non-greedy match on filler
re57 = '.'  # Uninteresting: c
re58 = '.*?'  # Non-greedy match on filler
re59 = '.'  # Uninteresting: c
re60 = '.*?'  # Non-greedy match on filler
re61 = '.'  # Uninteresting: c
re62 = '.*?'  # Non-greedy match on filler
re63 = '.'  # Uninteresting: c
re64 = '.*?'  # Non-greedy match on filler
re65 = '.'  # Uninteresting: c
re66 = '.*?'  # Non-greedy match on filler
re67 = '.'  # Uninteresting: c
re68 = '.*?'  # Non-greedy match on filler
re69 = '.'  # Uninteresting: c
re70 = '.*?'  # Non-greedy match on filler
re71 = '.'  # Uninteresting: c
re72 = '.*?'  # Non-greedy match on filler
re73 = '.'  # Uninteresting: c
re74 = '.*?'  # Non-greedy match on filler
re75 = '.'  # Uninteresting: c
re76 = '.*?'  # Non-greedy match on filler
re77 = '.'  # Uninteresting: c
re78 = '.*?'  # Non-greedy match on filler
re79 = '.'  # Uninteresting: c
re80 = '.*?'  # Non-greedy match on filler
re81 = '.'  # Uninteresting: c
re82 = '.*?'  # Non-greedy match on filler
re83 = '.'  # Uninteresting: c
re84 = '.*?'  # Non-greedy match on filler
re85 = '.'  # Uninteresting: c
re86 = '.*?'  # Non-greedy match on filler
re87 = '.'  # Uninteresting: c
re88 = '.*?'  # Non-greedy match on filler
re89 = '.'  # Uninteresting: c
re90 = '.*?'  # Non-greedy match on filler
re91 = '.'  # Uninteresting: c
re92 = '.*?'  # Non-greedy match on filler
re93 = '.'  # Uninteresting: c
re94 = '.*?'  # Non-greedy match on filler
re95 = '.'  # Uninteresting: c
re96 = '.*?'  # Non-greedy match on filler
re97 = '.'  # Uninteresting: c
re98 = '.*?'  # Non-greedy match on filler
re99 = '.'  # Uninteresting: c
re100 = '.*?'  # Non-greedy match on filler
re101 = '.'  # Uninteresting: c
re102 = '.*?'  # Non-greedy match on filler
re103 = '.'  # Uninteresting: c
re104 = '.*?'  # Non-greedy match on filler
re105 = '.'  # Uninteresting: c
re106 = '.*?'  # Non-greedy match on filler
re107 = '.'  # Uninteresting: c
re108 = '.*?'  # Non-greedy match on filler
re109 = '.'  # Uninteresting: c
re110 = '.*?'  # Non-greedy match on filler
re111 = '.'  # Uninteresting: c
re112 = '.*?'  # Non-greedy match on filler
re113 = '.'  # Uninteresting: c
re114 = '.*?'  # Non-greedy match on filler
re115 = '.'  # Uninteresting: c
re116 = '.*?'  # Non-greedy match on filler
re117 = '.'  # Uninteresting: c
re118 = '.*?'  # Non-greedy match on filler
re119 = '.'  # Uninteresting: c
re120 = '.*?'  # Non-greedy match on filler
re121 = '.'  # Uninteresting: c
re122 = '.*?'  # Non-greedy match on filler
re123 = '.'  # Uninteresting: c
re124 = '.*?'  # Non-greedy match on filler
re125 = '(.)'  # Any Single Character 3
re126 = '(.)'  # Any Single Character 4

rg = re.compile(
    re1 + re2 + re3 + re4 + re5 + re6 + re7 + re8 + re9 + re10 + re11 + re12 + re13 + re14 + re15 + re16 + re17 +
    re18 + re19 + re20 + re21 + re22 + re23 + re24 + re25 + re26 + re27 + re28 + re29 + re30 + re31 + re32 + re33 +
    re34 + re35 + re36 + re37 + re38 + re39 + re40 + re41 + re42 + re43 + re44 + re45 + re46 + re47 + re48 + re49 +
    re50 + re51 + re52 + re53 + re54 + re55 + re56 + re57 + re58 + re59 + re60 + re61 + re62 + re63 + re64 + re65 +
    re66 + re67 + re68 + re69 + re70 + re71 + re72 + re73 + re74 + re75 + re76 + re77 + re78 + re79 + re80 + re81 + re82 + re83 + re84 + re85 + re86 + re87 + re88 + re89 + re90 + re91 + re92 + re93 + re94 + re95 + re96 + re97 + re98 + re99 + re100 + re101 + re102 + re103 + re104 + re105 + re106 + re107 + re108 + re109 + re110 + re111 + re112 + re113 + re114 + re115 + re116 + re117 + re118 + re119 + re120 + re121 + re122 + re123 + re124 + re125 + re126,
    re.IGNORECASE | re.DOTALL)
m = rg.search(txt)
if m:
    c1 = m.group(1)
    c2 = m.group(2)
    w1 = m.group(3)
    w2 = m.group(4)
    w3 = m.group(5)
    c3 = m.group(6)
    c4 = m.group(7)
    print
    "(" + c1 + ")" + "(" + c2 + ")" + "(" + w1 + ")" + "(" + w2 + ")" + "(" + w3 + ")" + "(" + c3 + ")" + "(" + c4 + ")" + "\n"
